name: Build Android JRE (aarch64)

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/build-android-jre.yml'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential autoconf automake libtool pkg-config gawk gperf make cmake \
            zip unzip curl xz-utils python2 git ccache zlib1g-dev

      - name: Download NDK r10e (retry + fallback mirrors)
        run: |
          set -euxo pipefail
          cd "$RUNNER_TEMP"
          urls=(
            "https://dl.google.com/android/repository/android-ndk-r10e-linux-x86_64.zip"
            "https://dl.google.com/android/ndk/android-ndk-r10e-linux-x86_64.zip"
            "https://archive.org/download/android-ndk-r10e/android-ndk-r10e-linux-x86_64.zip"
          )
          success=0
          for u in "${urls[@]}"; do
            echo "Trying $u"
            rm -f ndk.zip || true
            if curl -fL --retry 5 --retry-connrefused --retry-delay 2 -o ndk.zip "$u"; then
              if unzip -tq ndk.zip > /dev/null 2>&1; then
                echo "Downloaded a valid zip from $u"
                success=1
                break
              fi
            fi
          done
          if [ "$success" -ne 1 ]; then
            echo "Failed to download a valid NDK r10e archive from all sources" >&2
            exit 1
          fi
          unzip -q ndk.zip
          echo "ANDROID_NDK_HOME=$RUNNER_TEMP/android-ndk-r10e" >> "$GITHUB_ENV"

      - name: Force NDK scripts to python2
        run: |
          set -euxo pipefail
          if [ -f "$ANDROID_NDK_HOME/build/tools/make-standalone-toolchain.sh" ]; then
            sed -i 's@/usr/bin/env python@/usr/bin/env python2@' "$ANDROID_NDK_HOME/build/tools/make-standalone-toolchain.sh" || true
            sed -i 's/\<python\>/python2/g' "$ANDROID_NDK_HOME/build/tools/make-standalone-toolchain.sh" || true
          fi

      - name: Clone Android OpenJDK build scripts
        run: |
          git clone --depth=1 https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch.git build-android-jdk

      - name: Build JDK 17 (aarch64)
        working-directory: build-android-jdk
        env:
          ANDROID_NDK_HOME: ${{ env.ANDROID_NDK_HOME }}
          TARGET: aarch64-linux-android
          TARGET_JDK: aarch64
          ANDROID_API_LEVEL: 21
          JDK_DEBUG_LEVEL: release
          JVM_VARIANTS: server
          BUILD_FREETYPE_VERSION: 2.10.4
          JDK_MAJOR: 17
          PYTHON: /usr/bin/python2
        run: |
          set -euxo pipefail
          ./extractndk.sh
          ./maketoolchain.sh
          ./getlibs.sh
          ./buildlibs.sh
          ./clonejdk.sh
          ./buildjdk.sh
          ./removejdkdebuginfo.sh
          ./tarjdk.sh
          ls -lah out || true
          ls -lah images || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jre-aarch64-jdk17
          path: |
            build-android-jdk/out/**
            build-android-jdk/images/**
            
